[package]
name = "executor"
version = "0.1.0"
authors = ["Alyssa Verkade <alyssaverkade@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
neuromancer = { path = "../neuromancer" }
hash-rings = "1.1"
tonic = "0.2"
prost = "0.6"
futures = "0.3"
snafu = "0.6"
ulid = "0.3.1"
bytes = "0.5"
