[package]
name = "executor"
version = "0.1.0"
authors = ["Alyssa Verkade <alyssaverkade@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
tonic = "0.2"
prost = "0.6"
futures = "0.3"
snafu = "0.6"
uuid = "0.8.1"
bytes = "0.5"

[dependencies.neuromancer]
path = "../neuromancer"
